name: Run on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container: python:3.12.4
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Убедитесь, что файл requirements.txt содержит зависимости проекта
      
      - name: Run migration conflicts check
        run: |
          python myproject/manage.py makemigrations --check
        env:
          DJANGO_SETTINGS_MODULE: myproject/myapp.settings