name: Test

on: 
  pull_request:


jobs:
  validate-pr:
    name: Testing

    runs-on: ubuntu-latest
    container: python:3.12.4

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migration conflicts check
        run: |
          echo "success"
        env:
          DJANGO_SETTINGS_MODULE: myproject.settings
          PYTHONPATH: ${{ github.workspace }}


on: 
  merge_group:


jobs:
  validate-pr:
    name: Premerge

    runs-on: ubuntu-latest
    container: python:3.12.4
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migration conflicts check
        run: |
          python myproject/manage.py makemigrations --check
        env:
          DJANGO_SETTINGS_MODULE: myproject.settings
          PYTHONPATH: ${{ github.workspace }}