# Generated by Django 5.2 on 2025-04-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_model3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=50)),
            ],
        ),
    ]
