# Generated by Django 5.2 on 2025-04-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_model4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model4',
        ),
    ]
