# Generated by Django 5.2 on 2025-04-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_model4'),
    ]

    operations = [
        migrations.AddField(
            model_name='model4',
            name='field2',
            field=models.IntegerField(default=0),
        ),
    ]
