# Generated by Django 5.2 on 2025-04-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_model4'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3',
            name='field2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
