# Generated by Django 5.2 on 2025-04-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_model3_field2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=50)),
            ],
        ),
    ]
